'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Stellar_Politics.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bigplanetBarren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetBarren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetDesert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetDesert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetEden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetEden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetGaseous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetGaseous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetOcean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetOcean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetSprawl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetSprawl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetVolcanic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetVolcanic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigplanetWasteland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigplanetWasteland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property binaryStarBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binaryStarBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property detailsBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("detailsBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property galaxy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galaxy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBGBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBGBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBGBlueWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBGBlueWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBGOrangeRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBGOrangeRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBGRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBGRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBGWhiteYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBGWhiteYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starBlueWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starBlueWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starOrangeRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starOrangeRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starWhiteYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starWhiteYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
